--CERTIFICADO_CONFIG
INSERT INTO CERTIFICADO_CONFIG VALUES ('VSB-1684-SCNP-50-3386.2-330', 6, 'VSB-1684-SCNP-50-3386.2-330.jpg')
GO
--CERTIFICADO_CONFIG_DET
INSERT INTO CERTIFICADO_CONFIG_DET VALUES ((SELECT MAX(ID) FROM CERTIFICADO_CONFIG), 'PIEZAS.colada', NULL, NULL, 0, NULL, 'Nro Colada', 1, 0, 0, 2)
INSERT INTO CERTIFICADO_CONFIG_DET VALUES ((SELECT MAX(ID) FROM CERTIFICADO_CONFIG), 'PIEZAS.PIEZA', NULL, NULL, 0, NULL, 'Nro Pieza', 1, 0, 0, 2)
INSERT INTO CERTIFICADO_CONFIG_DET VALUES ((SELECT MAX(ID) FROM CERTIFICADO_CONFIG), 'CUSTOMER_ORDER.CUSTOMER_ID', NULL, NULL, 0, NULL, 'Id Cliente', 1, 0, 0, 2)
INSERT INTO CERTIFICADO_CONFIG_DET VALUES ((SELECT MAX(ID) FROM CERTIFICADO_CONFIG), 'CUSTOMER.NAME', NULL, NULL, 0, NULL, 'Cliente', 1, 0, 0, 4)
INSERT INTO CERTIFICADO_CONFIG_DET VALUES ((SELECT MAX(ID) FROM CERTIFICADO_CONFIG), 'HR.OC_CLIENTE', NULL, NULL, 0, NULL, 'OC Cliente', 1, 0, 0, 2)
INSERT INTO CERTIFICADO_CONFIG_DET VALUES ((SELECT MAX(ID) FROM CERTIFICADO_CONFIG), 'HR.PLCLIENTE', NULL, NULL, 0, NULL, 'Plano Cliente', 1, 0, 0, 2)
INSERT INTO CERTIFICADO_CONFIG_DET VALUES ((SELECT MAX(ID) FROM CERTIFICADO_CONFIG), 'HR.REVCLIENTE', NULL, NULL, 0, NULL, 'Rev.Plano Cliente', 1, 0, 0, 2)
INSERT INTO CERTIFICADO_CONFIG_DET VALUES ((SELECT MAX(ID) FROM CERTIFICADO_CONFIG), 'HR.DIAMETROTABLA', NULL, NULL, 0, NULL, 'Diámetro Tabla', 1, 0, 0, 2)
INSERT INTO CERTIFICADO_CONFIG_DET VALUES ((SELECT MAX(ID) FROM CERTIFICADO_CONFIG), 'HR.LTABLA', NULL, NULL, 0, NULL, 'Largo Tabla', 1, 0, 0, 2)
INSERT INTO CERTIFICADO_CONFIG_DET VALUES ((SELECT MAX(ID) FROM CERTIFICADO_CONFIG), 'HR.TIPODEMATERIAL', NULL, NULL, 0, NULL, 'Tipo Material', 1, 0, 0, 2)
INSERT INTO CERTIFICADO_CONFIG_DET VALUES ((SELECT MAX(ID) FROM CERTIFICADO_CONFIG), 'HR.OF_FSC', NULL, NULL, 0, NULL, 'OC FSC', 1, 0, 0, 2)
INSERT INTO CERTIFICADO_CONFIG_DET VALUES ((SELECT MAX(ID) FROM CERTIFICADO_CONFIG), 'PIEZAS.cliente', NULL, NULL, 0, NULL, 'Nro Parte', 1, 0, 0, 2)
INSERT INTO CERTIFICADO_CONFIG_DET VALUES ((SELECT MAX(ID) FROM CERTIFICADO_CONFIG), 'HR.PLFSC', NULL, NULL, 0, NULL, 'Plano FSC', 1, 0, 0, 2)
INSERT INTO CERTIFICADO_CONFIG_DET VALUES ((SELECT MAX(ID) FROM CERTIFICADO_CONFIG), 'HR.REVFSC', NULL, NULL, 0, NULL, 'Rev.Plano FSC', 1, 0, 0, 2)
INSERT INTO CERTIFICADO_CONFIG_DET VALUES ((SELECT MAX(ID) FROM CERTIFICADO_CONFIG), 'HR.APLICACION', NULL, NULL, 0, NULL, 'Aplicación', 1, 0, 0, 2)
INSERT INTO CERTIFICADO_CONFIG_DET VALUES ((SELECT MAX(ID) FROM CERTIFICADO_CONFIG), 'HR.PESOFINAL', NULL, NULL, 0, NULL, 'Peso Final', 1, 0, 0, 2)

INSERT INTO CERTIFICADO_CONFIG_DET VALUES ((SELECT MAX(ID) FROM CERTIFICADO_CONFIG), 'Ensayo1', NULL, NULL, 1, 5, 'Ensayo1', 1, 0, 0, 3)
INSERT INTO CERTIFICADO_CONFIG_DET VALUES ((SELECT MAX(ID) FROM CERTIFICADO_CONFIG), 'Ensayo2', NULL, NULL, 1, 5, 'Ensayo2', 1, 0, 0, 3)
INSERT INTO CERTIFICADO_CONFIG_DET VALUES ((SELECT MAX(ID) FROM CERTIFICADO_CONFIG), 'Ensayo3', NULL, NULL, 1, 5, 'Ensayo3', 1, 0, 0, 3)

INSERT INTO CERTIFICADO_CONFIG_DET VALUES ((SELECT MAX(ID) FROM CERTIFICADO_CONFIG), 'TextoObservaciones', NULL, NULL, 1, 1, 'Observaciones', 1, 0, 0, 4)
INSERT INTO CERTIFICADO_CONFIG_DET VALUES ((SELECT MAX(ID) FROM CERTIFICADO_CONFIG), 'NumeroCertificado', NULL, NULL, 0, 1, 'Nro.Certificado', 0, 0, 0, 2)

GO